name: Wheels

on: [push, pull_request]

env:
  REPO_DIR: .
  BUILD_DEPENDS: ""
  TEST_DEPENDS: "pytest pytest-cov"
  WHEEL_SDIR: wheelhouse

jobs:
  build:
    name: Build wheel ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04", "windows-2019", "macos-10.15" ]
    env:
      BUILD_COMMIT: HEAD
      CIBW_BEFORE_ALL_LINUX: sh ci/docker-fixes.sh
      CIBW_ARCHS_MACOS: x86_64 arm64 universal2
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl
