name: Wheels

on: [push, pull_request]

env:
  REPO_DIR: .
  BUILD_DEPENDS: ""
  TEST_DEPENDS: "pytest pytest-cov"
  WHEEL_SDIR: wheelhouse

jobs:
  build:
    name: Build wheel ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-10.15" ]
    env:
      BUILD_COMMIT: HEAD
      CIBW_BEFORE_ALL_LINUX: sh ci/docker-fixes.sh
      CIBW_BEFORE_ALL_MACOS: sh ci/osx-fixes.sh
      CIBW_ARCHS_MACOS: x86_64 arm64 universal2
      CIBW_BUILD: "cp39-*"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update path
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "/usr/local/opt/libtool/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/ragel/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/automake/bin" >> $GITHUB_PATH
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.0.0a2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl
