name: Wheels

on: [push, pull_request]

env:
  REPO_DIR: .
  BUILD_DEPENDS: ""
  TEST_DEPENDS: "pytest pytest-cov"
  WHEEL_SDIR: wheelhouse

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os-name }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04", "macos-latest" ]
        python: [ "pypy3.7-7.3.3","pypy3.6-7.3.3", "3.6", "3.7", "3.8", "3.9" ]
        platform: [ "x86_64", "i686" ]
        macos-target: [ "10.10" ]
        exclude:
          - os: "macos-latest"
            platform: "i686"
        include:
          - os: "macos-latest"
            os-name: "osx"
          - os: "ubuntu-20.04"
            os-name: "focal"
          - os: "macos-11.0"
            os-name: "osx"
            platform: "arm64"
            python: "3.9"
            macos-target: "11.0"
          - os: "macos-11.0"
            os-name: "osx"
            platform: "arm64"
            python: "3.8"
            macos-target: "11.0"
    env:
      BUILD_COMMIT: HEAD
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macos-target }}
      CONFIG_PATH: "ci/multibuild_config.sh"
      ENV_VARS_PATH: "ci/env_vars.sh"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build Wheel
        run: .github/workflows/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl
